theme: jekyll-theme-cayman

title: Sudhanshu Chauhan
description: Data Architect / Engineer & Data Science Enthusiast

social-network-links:
  email: mailbox.sud@gmail.com
  github: sudhanshu-chauhan
  twitter: Sud_daemon
